[project]
name = "cuda-experiments"
version = "0.1.0"
description = "A few CUDA experiments"
authors = ["Zihua Wu <zihuaw@nvidia.com>"]
channels = ["nvidia", "pytorch", "conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
cuda-compiler = ">=12.1,<12.2"
cuda-cudart-dev = ">=12.1,<12.2"
cuda-cudart-static = ">=12.1,<12.2"
pytorch-cuda = ">=12.1,<12.2"
pytorch = ">=2.1.2,<2.2"
numpy = ">=1.26.3,<1.27"
cmake = ">=3.28.1,<3.29"
nccl = ">=2.19.4.1,<2.19.5"
cutensor = ">=2.0.0,<2.1"

[pypi-dependencies]
cupy-cuda12x = "*"

[system-requirements]
libc = { family = "glibc", version = "2.17" }
